name: arpsEnKFtools
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python 
  - metpy
  - numpy
  - matplotlib
  - ipython
  - jupyter
  - codecov 
  - coverage 
  - autopep8 
  - flake8 
  - pylint 
  - pytest 
  - sphinx 
  - sphinx-copybutton 
  - numpydoc
  - siphon
  - pip:
    - nexradaws
    - "-e git+https://github.com/readthedocs/sphinx_rtd_theme.git@2b8717a3647cc650625c566259e00305f7fb60aa#egg=sphinx_rtd_theme"
    - "--editable=git+https://github.itap.purdue.edu/STorMLab/pyCRMtools.git@master#egg=pyCRMtools"
